services:
  manager:
    build:
      context: ./manager
      dockerfile: Dockerfile
    image: manager:latest
    environment:
      - RUST_LOG=info
      - DATABASE_URL=postgresql://postgres:password@manager-db:5432/manager-db
      - EXPOSE_URL=0.0.0.0
    ports:
      - 8081:8081
    depends_on:
      manager-db:
        condition: service_healthy

  python-extractor:
    build:
      context: .
      dockerfile: ./python-extractor/Dockerfile
    image: python-extractor:latest
    environment:
      - MANAGER_URL=http://manager:8081
      - SYNTHESIZER_URL=http://synthesizer:8080
      - EXPOSE_URL=0.0.0.0
    ports:
      - 8082:8082
    depends_on:
      - manager
      - synthesizer

  synthesizer:
    build:
      context: .
      dockerfile: ./synthesizer/Dockerfile
    image: synthesizer:latest
    environment:
      - CM_NEO4J_URI=bolt://cm_neo4j:7687
      - CM_NEO4J_USERNAME=neo4j
      - CM_NEO4J_PASSWORD=password
      - SDG_NEO4J_URI=bolt://sdg_neo4j:7687
      - SDG_NEO4J_USERNAME=neo4j
      - SDG_NEO4J_PASSWORD=password
      - IMCG_NEO4J_URI=bolt://imcg_neo4j:7687
      - IMCG_NEO4J_USERNAME=neo4j
      - IMCG_NEO4J_PASSWORD=password
      - EXPOSE_URL=0.0.0.0
    ports:
      - 8080:8080
    depends_on:
      cm_neo4j:
        condition: service_healthy
      sdg_neo4j:
        condition: service_healthy
      imcg_neo4j:
        condition: service_healthy

  cm_neo4j:
    image: neo4j:latest
    container_name: cm_neo4j
    environment:
      NEO4J_AUTH: "neo4j/password"
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # BOLT
    healthcheck:
      test:
        ["CMD-SHELL", "cypher-shell -u neo4j -p password 'RETURN 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  sdg_neo4j:
    image: neo4j:latest
    container_name: sdg_neo4j
    environment:
      NEO4J_AUTH: "neo4j/password"
    ports:
      - "7475:7474"
      - "7688:7687"
    healthcheck:
      test:
        ["CMD-SHELL", "cypher-shell -u neo4j -p password 'RETURN 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  imcg_neo4j:
    image: neo4j:latest
    container_name: imcg_neo4j
    environment:
      NEO4J_AUTH: "neo4j/password"
    ports:
      - "7476:7474"
      - "7689:7687"
    healthcheck:
      test:
        ["CMD-SHELL", "cypher-shell -u neo4j -p password 'RETURN 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  manager-db:
    image: postgres:16
    container_name: manager-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: manager-db
    ports:
      - "5432:5432"
    volumes:
      - manager-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d manager-db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  manager-db-data:
