[package]
name = "synthesizer"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
tokio = { version = "1.46.1", features = ["rt-multi-thread", "macros"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
env_logger = "0.11.8"
log = "0.4.27"
utoipa = { version = "5.4.0", features = ["macros", "actix_extras", "uuid"] }
utoipa-swagger-ui = { version = "9", features = ["actix-web"] }
dotenvy = "0.15.0"
neo4rs = "0.8.0"
uuid = { version = "1.17.0", features = ["serde", "v4"] }
testcontainers = "0.18.0"
strsim = "0.11"
models = { path = "../models" }
thiserror = "2.0.3"
rust-s3 = "0.37.0"
futures = "0.3.31"
