[package]
name = "synthesizer"
version = "0.1.0"
edition = "2024"

[dependencies]
models = { workspace = true }
clients = { workspace = true }

actix-web = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
serde = { workspace = true }
serde_json = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
utoipa = { workspace = true }
utoipa-swagger-ui = { workspace = true }
dotenvy = { workspace = true }
neo4rs = { workspace = true }
uuid = { workspace = true }
testcontainers = { workspace = true }
strsim = { workspace = true }
thiserror = { workspace = true }
rust-s3 = { workspace = true }
futures = { workspace = true }
chrono = { workspace = true }
awc = { workspace = true }
regex = { workspace = true }

[dev-dependencies]
extractor-runtime = { workspace = true }
go-extractor = { workspace = true }
