services:
  cm_neo4j:
    image: neo4j:latest
    container_name: cm_neo4j
    environment:
      NEO4J_AUTH: "neo4j/password"
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # BOLT

  sdg_neo4j:
    image: neo4j:latest
    container_name: sdg_neo4j
    environment:
      NEO4J_AUTH: "neo4j/password"
    ports:
      - "7475:7474"
      - "7688:7687"

  imcg_neo4j:
    image: neo4j:latest
    container_name: imcg_neo4j
    environment:
      NEO4J_AUTH: "neo4j/password"
    ports:
      - "7476:7474"
      - "7689:7687"

  # TODO: Now it doesn't matter, but in future it would be suitable to introduce script for:
  # cleaning unused objects, since we are only using object storage for transfering data,
  # the timeframe for cleaning can be set to hours/minutes.
  # Then we want the script to be able to implicitly create "code-elements" bucket.
  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "8333:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: accesskey
      MINIO_ROOT_PASSWORD: secretkey
    volumes:
      - ../data/minio:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio-setup:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 accesskey secretkey;
      /usr/bin/mc mb myminio/code-elements || true;
      exit 0;
      "
