[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
extractor-runtime = { workspace = true }
synthesizer = { workspace = true }
models = { workspace = true }
sage = { workspace = true }

clap = { workspace = true }
tokio = { workspace = true, features = ["full"] }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
env_logger = { workspace = true }
env-scraper = { path = "../env-scraper" }
