[package]
name = "extractor-runtime"
version = "0.1.0"
edition = "2024"

[dependencies]
models = { workspace = true }
statix = { workspace = true }
clients = { workspace = true }
python-extractor = { workspace = true }
java-extractor = { workspace = true }

actix-web = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
serde = { workspace = true }
serde_json = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
utoipa = { workspace = true }
utoipa-swagger-ui = { workspace = true }
dotenvy = { workspace = true }
uuid = { workspace = true }
actix-multipart = { workspace = true }
futures-util = { workspace = true }
awc = { workspace = true }
thiserror = { workspace = true }
chrono = { workspace = true }
rust-s3 = { workspace = true }
actix-cors = { workspace = true }
async-trait = { workspace = true }
once_cell = { workspace = true }
regex = { workspace = true }
strsim = { workspace = true }