[package]
name = "extractor-runtime"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.12.0"
tokio = { version = "1.48.0", features = ["rt-multi-thread", "macros"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
env_logger = "0.11.8"
log = "0.4.28"
utoipa = { version = "5.4.0", features = ["macros", "actix_extras", "uuid"] }
utoipa-swagger-ui = { version = "9", features = ["actix-web"] }
dotenvy = "0.15"
uuid = { version = "1.18.1", features = ["serde", "v4"] }
actix-multipart = "0.7.2"
futures-util = "0.3"
awc = "3.8.1" 
thiserror = "2.0.17"
chrono = { version = "0.4", features = ["serde"] }
rust-s3 = "0.37.0"
actix-cors = "0.7.1"
async-trait = "0.1.89"
once_cell = "1.21.3"

models = { path = "../models" }
clients = { path = "../clients" }
python-extractor = { path = "../python-extractor"} 
java-extractor ={ path = "../java-extractor" }
