mod attribute_resolution;
mod class_hierarchy;
mod cross_file_resolution;
mod entity_field_resolution;
mod framework_endpoints;
mod identification;
mod module_resolution;
mod pass3_evaluation;
mod type_inference;
