pub mod api;
pub mod assignments;
pub mod callables;
pub mod calls;
pub mod common;
pub mod communication;
pub mod configuration;
pub mod endpoints;
pub mod entities;
pub mod enums;
pub mod imports;
pub mod ir;
pub mod proto;
pub mod restcalls;

pub use api::CodeElementsAggregate;
pub use assignments::{Assignment, AssignmentKey, Scope};
pub use callables::{Callable, Namespace, Parameter, ParsedCallable};
pub use calls::{Argument, CallStatement};
pub use common::HttpMethod;
pub use communication::{CommunicationProtocol, MessageDestinationKind, MessageEdge, MessageRole};
pub use configuration::ConfigurationData;
pub use endpoints::Endpoint;
pub use entities::{Entity, Field};
pub use imports::Import;
pub use proto::ProtoService;
pub use restcalls::RestCall;
