[package]
name = "python-extractor"
version = "0.1.0"
edition = "2024"

[dependencies]
models = { workspace = true }
statix = { workspace = true }

tree-sitter = { workspace = true }
tree-sitter-python = { workspace = true }
regex = { workspace = true }
sha2 = { workspace = true }
once_cell = { workspace = true }
log = { workspace = true }
rayon = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
