[package]
name = "java-extractor"
version = "0.1.0"
edition = "2024"

[dependencies]
models = { workspace = true }
statix = { workspace = true }

tree-sitter = { workspace = true }
tree-sitter-java = { workspace = true }
regex = { workspace = true }
once_cell = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
log = { workspace = true }
rayon = { workspace = true }
