[package]
name = "java-extractor"
version = "0.1.0"
edition = "2024"

[dependencies]
tree-sitter = "0.25.7"
tree-sitter-java = "0.23.5"
regex = "1.11.1"
sha2 = "0.10.9"
once_cell = "1.21.3"
tokio = { version = "1.46.1", features = ["rt-multi-thread", "macros"] }
log = "0.4.27"

models = { path = "../models" }